language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "pypy3"
  
install:
  - pip install .  # Install your package
  - pip install pytest  # Install pytest for testing
  
script:
  - pytest  # Run the tests using pytest
